### ISSUE TITLE
Contrast Issues on About Page

### ISSUE THREAD

**Issue by csgreer6** [religious-ecologies/website#28] opened 2020-10-29 17:17 UTC
The suggested citation on the About page has too low of a contrast - found using WAVE on a Mac.

Screenshots attached.
![low contrast on about page](https://user-images.githubusercontent.com/70596028/97608620-f5178b00-19e8-11eb-9a0c-c24e4ce0d27e.png)
![Screen Shot 2020-10-29 at 1 16 44 PM](https://user-images.githubusercontent.com/70596028/97608682-095b8800-19e9-11eb-9d55-d04ade36a58a.png)

**Comment by kimisgold** [comment] 2020-12-11 17:28
duplicate of #27

**Closed by kimisgold** 2020-12-11 17:28 UTC
Labels: accessibiltiy
